#!/bin/bash
HOSTNAME=`sudo hostname`
echo HOSTNAME = $HOSTNAME
TIMEZONE=`sudo timedatectl | grep zone | awk '{print $1="", $2="", $0}'`
echo TIMEZONE = $TIMEZONE
USER=`whoami`
echo USER = $USER
OS=`hostnamectl | grep Operating | awk '{print $1="", $2="", $0}'`
echo OS = $OS
DATE=`date "+%d %b %Y %T"`
echo DATE = $DATE
UPTIME=`uptime | awk '{print $1"\t"$3}'`
echo UPTIME = $UPTIME
UPTIME_SEC=`awk '{print $1}' /proc/uptime`
echo UPTIME_SEC = $UPTIME_SEC
IP=`ifconfig enp0s3 | grep -e inet -e "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -1 | awk '{print $2}'`
echo IP = $IP
MASK=`ifconfig enp0s3 | grep netmask | awk '{printf $4}'`
echo MASK = $MASK
GATEWAY=`ip route | grep default | awk '{print $3}'`
echo GATEWAY = $GATEWAY
RAM_TOTAL=`free -m | awk /Mem:/'{printf "%.3f Gb ", $2/1024}'`
echo RAM_TOTAL = $RAM_TOTAL
RAM_USED=`free -m | awk /Mem:/'{printf "%.3f Gb ", $3/1024}'`
echo RAM_USED = $RAM_USED
RAM_FREE=`free -m | awk /Mem:/'{printf "%.3f Gb ", $4/1024}'`
echo RAM_FREE = $RAM_FREE
SPACE_ROOT=`df /  | awk '/dev/ {printf "%.2f Mb ", $2/1024}'`
echo SPACE_ROOT = $SPACE_ROOT
SPACE_ROOT_USED=`df / | awk '/dev/ {printf "%.2f Mb ", $3/1024}'`
echo SPACE_ROOT_USED = $SPACE_ROOT_USED
SPACE_ROOT_FREE=`df / | awk '/dev/ {printf "%.2f Mb ", $4/1024}'`
echo SPACE_ROOT_FREE = $SPACE_ROOT_FREE
